version: "3.8"

volumes:
  contagem_mongo_data:

networks:
  internal:
    external: false

services:
  contagem:
    container_name: "contagem_api"
    restart: always
    image: ameciclo/contagem
    build: .
    command: ["npm", "run", "dev"]
    volumes:
      - .:/contagem
    environment:
      APP_PORT: 4000
      APP_HOST: 0.0.0.0
      DB_NAME: dev
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME: test
      DB_PASSWORD: test
      NODE_ENV: development
    ports:
      - "4000:4000"
    networks:
      - internal
    links:
      - mongo
  mongo:
    container_name: "contagem_db"
    image: mongo
    restart: always
    networks:
      - internal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - contagem_mongo_data:/data/db
