version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: ameciclo/contagem_de_ciclistas
    docker:
      - image: circleci/buildpack-deps:stretch
orbs:
  node: circleci/node@4.4.0

jobs:
  build-and-test:  
    docker:
      - image: cimg/node:lts

    working_directory: ~/ameciclo/contagem_de_ciclistas

    steps:
      - checkout:
          path: ~/ameciclo/contagem_de_ciclistas
      - node/install-packages
      - run:
          name: Run build
          command: npm run build

workflows:
  build-latest: 
    jobs:
      - build-and-test